language: node_js
node_js: stable
branches:
  only:
  - hexo
before_install:
- npm install -g hexo
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo g
after_success:
  - cd ./public
  - git init
  - git config --global user.name 'aspirinmrmi'
  - git config --global user.email 'mhb7724@qq.com'
  - git add .
  - git commit -m "generate static resources, triggerd by travis ci"
  - git push --force "https://AspirinMrmi:${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: https://github.com/AspirinMrmi/AspirinMrmi.github.io.git